# Generated by Django 3.1.3 on 2022-04-03 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, max_length=256, upload_to='news_img/%Y/%m/', verbose_name='展示图片')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ('-created',),
            },
        ),
    ]
